# Generated by Django 3.2 on 2023-03-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='post_file',
            name='fil',
            field=models.FileField(upload_to='media/%Y/%m/%d/', verbose_name='file'),
        ),
    ]
