# Generated by Django 3.2 on 2023-03-31 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
